# Generated by Django 3.2.7 on 2021-10-02 16:49

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bid_alert_trigger',
            field=models.FloatField(default=90.0),
        ),
        migrations.AddField(
            model_name='user',
            name='funds',
            field=models.DecimalField(decimal_places=3, default=Decimal('1000000.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='max_bid_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.00'), max_digits=10),
        ),
    ]
