# Generated by Django 3.2.7 on 2021-10-01 21:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bid',
        ),
        migrations.AlterField(
            model_name='product',
            name='min_bid',
            field=models.DecimalField(blank=True, decimal_places=3, default=Decimal('10.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))]),
        ),
    ]
