# Generated by Django 3.2.7 on 2021-10-01 21:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_rename_bids_bid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='bid',
            name='auto_bid',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))]),
        ),
    ]
