# Generated by Django 3.2.7 on 2021-10-01 21:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_auto_20211001_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='version',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
