# Generated by Django 3.2.7 on 2021-10-01 22:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0006_alter_bid_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='version',
            field=models.UUIDField(blank=True, default=uuid.UUID('36f4744b-e9ff-429a-ae06-d0834845e25a')),
        ),
    ]
