# Generated by Django 3.2.7 on 2021-10-02 09:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0008_auto_20211002_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='version',
            field=models.UUIDField(blank=True, default=uuid.UUID('9724c6f6-3005-4aa3-8441-24a0645dca1a')),
        ),
    ]
